**ANN**

Importing libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

Importing dataset

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(Y)

[1 0 1 ... 1 1 0]


Encoding categorical data (Label Encoding the gender column)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the geography column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into the training set and test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Building the ANN
Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Training the ANN
Compiling the ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)


Epoch 1/100


250/250 [==============================] - 4s 4ms/step - loss: 0.5238 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4404 - accuracy: 0.7970
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4332 - accuracy: 0.8043
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4280 - accuracy: 0.8126
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4234 - accuracy: 0.8158
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4202 - accuracy: 0.8204
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4175 - accuracy: 0.8227
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4155 - acc

250/250 [==============================] - 1s 3ms/step - loss: 0.3921 - accuracy: 0.8380
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3923 - accuracy: 0.8370
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3923 - accuracy: 0.8371
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3924 - accuracy: 0.8379
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3923 - accuracy: 0.8369
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3922 - accuracy: 0.8367
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3921 - accuracy: 0.8378
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3921 - accuracy: 0.8382
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3922 - accuracy: 0.8375
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3923 - accuracy: 

Predicting the test set result

In [19]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the confusion matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1550   45]
 [ 271  134]]


0.842